component_version: 1.0.0
maximum_availability_zones: 5

family: memcached1.4
# engine_version: 1.4.5
# minor_upgrade: true

security_groups:
-
  rules:
  -
    IpProtocol: tcp
    FromPort: 6379
    ToPort: 6379
  ips:
  - stack

ip_blocks:
  local:
  - 169.254.169.254/32
